# Generated by Django 4.2.4 on 2023-08-16 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0002_alter_lga_lga_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lga',
            name='lga_description',
            field=models.TextField(default='default description', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='polling_unit',
            name='polling_unit_description',
            field=models.TextField(default='default description', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ward',
            name='ward_description',
            field=models.TextField(default='default description', max_length=255, null=True),
        ),
    ]
